default_language_version:
    python: python3.11
default_install_hook_types: [pre-commit, pre-push]

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-merge-conflict
          - id: check-yaml
          - id: check-toml
          - id: detect-private-key

    # Use the project environment for lint/format/type-check/tests to avoid extra downloads
    - repo: local
      hooks:
          - id: ruff
            name: ruff (lint)
            entry: bash -lc 'eval "$(conda shell.bash hook)" && conda activate self-mem && ruff check . --fix'
            language: system
            types: [python]
            stages: [pre-commit]

          - id: ruff-format
            name: ruff (format)
            entry: bash -lc 'eval "$(conda shell.bash hook)" && conda activate self-mem && ruff format .'
            language: system
            types: [python]
            stages: [pre-commit]

          - id: mypy
            name: mypy
            entry: bash -lc 'eval "$(conda shell.bash hook)" && conda activate self-mem && mypy --config-file=pyproject.toml app'
            language: system
            types: [python]
            pass_filenames: false
            stages: [pre-commit]

          # Run full automated test suite (unit + integration) on commit to match CI
          - id: pytest-all
            name: pytest (unit + integration)
            entry: bash -lc 'eval "$(conda shell.bash hook)" && conda activate self-mem && PYTHONPATH=. pytest -q -m "unit or integration" --maxfail=1'
            language: system
            pass_filenames: false
            stages: [pre-commit]
