name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true

jobs:
    tests:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
            SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
            SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
            TEST_SUPABASE_TABLE_PREFIX: test_
            API_AUTH_KEY: test-api-key
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
                  cache: "pip"
                  cache-dependency-path: requirements-dev.txt

            - name: Ensure default API keys when secrets are missing
              shell: bash
              run: |
                  if [ -z "${OPENAI_API_KEY}" ]; then echo "OPENAI_API_KEY=dummy" >> "$GITHUB_ENV"; fi
                  if [ -z "${PINECONE_API_KEY}" ]; then echo "PINECONE_API_KEY=dummy" >> "$GITHUB_ENV"; fi

            - name: Install pinned dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements-dev.txt

            - name: Lint (ruff)
              run: ruff check .

            - name: Type check (mypy)
              run: mypy .

            - name: Tests (unit + integration, with coverage)
              run: pytest -m "unit or integration" -ra

            - name: Upload coverage HTML
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: htmlcov
                  path: htmlcov
                  if-no-files-found: ignore
